name: PHP Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup latest stable version of PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "latest"

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Setup sqlite test database
        run: touch database/database.sqlite

      - name: Prepare Laravel Application
        run: |
          cp .env.example .env
          php artisan key:generate
          php artisan migrate:fresh --seed

      - name: Run tests
        run: php artisan test

      - name: Run static analysis
        run: ./vendor/bin/phpstan analyse --memory-limit=2G --error-format=github
